chess_piece_models = {"white": {"Pawn": {"chess_piece_name": 'Pawn',
                                         "chess_piece_color": 'White',
                                         "chess_piece_symbol": 'P',
                                         "chess_piece_unicode": '\u2659',
                                         "chess_piece_relative_value": 1,
                                         "chess_piece_default_position": "a1"},
                                "Knight": {"chess_piece_name": 'Knight',
                                           "chess_piece_color": 'White',
                                           "chess_piece_symbol": 'N',
                                           "chess_piece_unicode": '\u2658',
                                           "chess_piece_relative_value": 3,
                                           "chess_piece_default_position": "b1"},
                                "Bishop": {"chess_piece_name": 'Bishop',
                                           "chess_piece_color": 'White',
                                           "chess_piece_symbol": 'B',
                                           "chess_piece_unicode": '\u2657',
                                           "chess_piece_relative_value": 3,
                                           "chess_piece_default_position": "c1"},
                                "Rook": {"chess_piece_name": 'Rook',
                                         "chess_piece_color": 'White',
                                         "chess_piece_symbol": 'R',
                                         "chess_piece_unicode": '\u2656',
                                         "chess_piece_relative_value": 5,
                                         "chess_piece_default_position": "a1"},
                                "Queen": {"chess_piece_name": 'Queen',
                                          "chess_piece_color": 'White',
                                          "chess_piece_symbol": 'Q',
                                          "chess_piece_unicode": '\u2655',
                                          "chess_piece_relative_value": 3,
                                          "chess_piece_default_position": "d1"},
                                "King": {"chess_piece_name": 'King',
                                         "chess_piece_color": 'White',
                                         "chess_piece_symbol": 'K',
                                         "chess_piece_unicode": '\u2654',
                                         "chess_piece_relative_value": 3,
                                         "chess_piece_default_position": "f3"}
                                },
                      "black": {"Pawn": {"chess_piece_name": 'Pawn',
                                         "chess_piece_color": 'Black',
                                         "chess_piece_symbol": 'p',
                                         "chess_piece_unicode": '\u265F',
                                         "chess_piece_relative_value": 1,
                                         "chess_piece_default_position": "c3"},
                                "Knight": {"chess_piece_name": 'Knight',
                                           "chess_piece_color": 'Black',
                                           "chess_piece_symbol": 'n',
                                           "chess_piece_unicode": '\u265E',
                                           "chess_piece_relative_value": 3,
                                           "chess_piece_default_position": "c3"},
                                "Bishop": {"chess_piece_name": 'Bishop',
                                           "chess_piece_color": 'Black',
                                           "chess_piece_symbol": 'b',
                                           "chess_piece_unicode": '\u265D',
                                           "chess_piece_relative_value": 3,
                                           "chess_piece_default_position": "c3"},
                                "Rook": {"chess_piece_name": 'Rook',
                                         "chess_piece_color": 'Black',
                                         "chess_piece_symbol": 'r',
                                         "chess_piece_unicode": '\u265C',
                                         "chess_piece_relative_value": 5,
                                         "chess_piece_default_position": "c3"},
                                "Queen": {"chess_piece_name": 'Queen',
                                          "chess_piece_color": 'Black',
                                          "chess_piece_symbol": 'q',
                                          "chess_piece_unicode": '\u265B',
                                          "chess_piece_relative_value": 10,
                                          "chess_piece_default_position": "c3"},
                                "King": {"chess_piece_name": 'King',
                                         "chess_piece_color": 'Black',
                                         "chess_piece_symbol": 'k',
                                         "chess_piece_unicode": '\u265A',
                                         "chess_piece_relative_value": 10,
                                         "chess_piece_default_position": "c3"}
                                },
                      }
